### ISSUE TITLE
Plan & apply in tf-apply-{env} job

### ISSUE THREAD

**Issue by NicholasAzar** [GoogleCloudPlatform/healthcare-data-protection-suite#1022]
Hi all,

Is there a reason we run a `terraform plan` before the `terraform apply -auto-approve` in our `tf-apply-{env}` cicd jobs? Was just looking over the docs for terraform apply and it seems that by default it runs the plan on its own anyway? 
docs: https://www.terraform.io/docs/cli/commands/apply.html#usage
config: https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/templates/tfengine/components/cicd/configs/tf-apply.yaml#L38

Further, if we did want to keep it as is, maybe the apply could reference the plan output so that we didn't create it again? This would also remove the chance of the state changing between plan & apply.

For example:
```
terraform plan -out tfplan
terraform apply -auto-approve "tfplan"
```

**Comment by thomasfung-hk** [comment]
The plan in stdout usually in `terraform apply` is actually part of the interactive approval process to show the user what resources will be modified, which is why `-auto-approve` will not show the plan in the output.

The change suggested makes sense. It's also similar to what is suggested on the Hashicorp Learn site: https://learn.hashicorp.com/tutorials/terraform/automate-terraform#automated-terraform-cli-workflow
