### ISSUE TITLE
CICD folder in live is not managed by terragrunt

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/healthcare-data-protection-suite#217]
There doesn't seem to be a terragrunt.hcl in the live/ cicd dir.

**Comment by xingao267** [comment]
This is intentional. The cicd in live is only needed when using with CICD and needs to be deployed before anything else. terragrunt plan-all or apply-all should not see this directory when run locally. It's done as a separate step in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/templates/tfengine/components/cicd/manual/configs/tf-plan.yaml#L30 and https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/templates/tfengine/components/cicd/manual/configs/tf-apply.yaml#L36

**Comment by umairidris** [comment]
So I was thinking of doing a similar thing to org_policies. You probably want org_policies to be deployed first as well so that later projects and deployments respect it, but do you think it's still worth it to allow terragrunt to deploy it? It may be more consistent to allow 'terragrunt apply' to work in any dir inside live while having our own CICD prioritize certain ones.

**Comment by xingao267** [comment]
Discussed offline. `live/cicd` folder is a special case where when you run `terragrunt apply-all` locally, `terragrunt` should just ignore that as it's a local deployment anyway. While when it's done through CD, CD will handle that `live/cicd` folder as part of the cloud build config. Will leave it as the way it is now and change if we later see a need.

org_policies is currently already handled by `terragrunt`, and it would be nice to deploy org_policies folder before the rest, but dependency between terragrunt folders are difficult. So that will be a separate topic which is nice to investigate and implement if possible in the future.
