### ISSUE TITLE
Engine schema should be more restrictive and do not allow additional properties

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/healthcare-data-protection-suite#295]
Engine should also set `additionalProperties = false` in schemas and make the validation more restrictive. This gives users more directions and error messages when their schema structure is wrong, or has typos or bad keywords. Otherwise, the engine might just run successfully but their engine configs can be written wrong, and changes didn't get picked up by the engine.

**Comment by xingao267** [comment]
I think this should have higher priority and start being looked into. This can help users a lot in understanding what went wrong and reduce silent errors.

**Comment by umairidris** [comment]
This is a bit non trivial because if we were to diasllow extra fields suddenly then there will be A LOT of duplication. Imagine every project having to duplicate the parent_id or location being set on every resource. We need a way to still have a list of 'common' top level data block that is acceptable
