### ISSUE TITLE
Add versioning

### ISSUE THREAD

**Issue by AdrianLsk** [GoogleCloudPlatform/healthcare-data-protection-suite#340]
Hi,

Thanks a lot for your effort with this project.

Would it be possible to start versioning the updates?

The latest change deleted the option to deploy only the simple architecture and it's impossible to recreate it with full as the new setup is dependent on the additional features.

Cheers,
Adrian

**Comment by umairidris** [comment]
Hi Adrian,

Thanks for your interest in the toolkit. As you know, the status of this product is EAP (early access program), which is why we have been making as many iterations as possible before stabilizing the toolkit. We will be going into alpha in a couple of weeks at which point we will start adding releases with change notes and upgrade steps whenever there is an impact to users.

Could you tell me how your use case was broken? It should still be possible to deploy a simple architecture using https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/org_foundation.hcl. There will be a complementary folder_foundation.hcl coming shortly to deploy the foundation within a folder.

**Comment by AdrianLsk** [comment]
Hi @umairidris 

OK, I wasn't aware of the plan. It's clear now. Thanks for the answer.

I made a silly mistake. I was expecting simple.hcl in my automation script. When it failed I completely overlooked the file org_foundation.hcl then.

I see you made the structure even clearer now.
Cheers

**Comment by umairidris** [comment]
FYI https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/issues/378 has been filed for making proper versioned releases with change notes which you may be interested in following. We hope to have something in place in a couple of weeks.
