### ISSUE TITLE
More documentation needed

### ISSUE THREAD

**Issue by jordan83** [GoogleCloudPlatform/healthcare-data-protection-suite#763]
You can glean a lot of insight from the existing examples, however they don't always work or represent what would be considered good practice. In particular, it is difficult to know how to handle dependencies between resources. The example below has a dependency between an Hl7V2 store and a pubsub topic. With no explicit link between the two the resources are deployed in the wrong order which causes an error.

https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/blob/master/examples/tfengine/modules/team.hcl#L270

In general, it is difficult to figure out how to handle dependencies using this module. My usual method is to look at what the engine spits out and then go read the documentation of the underlying modules to figure out what outputs I can use, etc. Documentation is a good start here but perhaps there is a better solution.

**Comment by umairidris** [comment]
#804

**Comment by xingao267** [comment]
Few more things I can think of that should be added later:

Template development guide in addition to current guide of adding new components

Common gotchas
- Use $ to escape $ in engine template
- `-` is automatically converted to `_` in Terraform resource names
- IAM policies do not support dynamic values due to underlying module and Terraform limitations. An common example is referencing service account resources in IAM policies, the workaround is to use `account_id` instead of `email`.
- Use `gcloud auth application-default login` for authentication, Terraform use ADC.

Tips
- use dot, e.g. {{.name}} to reference mandatory map fields
- use `get` func to reference optional map fields. The last argument is the default value
- use `range` to iterate over list
- Use `{{- ...}}` to remove empty lines before this block, and `{{... -}}` to remove empty lines after this block

@umairidris @MartinPetkov @jordan83 @yeweidaniel feel free to write down any tips you learned and common mistakes in this bug. I'll organize them and put them in a readme file later.

**Comment by xingao267** [comment]
When writing terraform configs, use `for_each` to group similar resources.

**Comment by xingao267** [comment]
For large block of raw terraform configs, consider using a separate template to dump raw terraform configs with value substitution instead of using `terraform_addons.raw_config`.

**Comment by umairidris** [comment]
Great tips. 

- I have been using 
  ```
  {{.... -}}}
  ...
  {{{end -}}
  ```

  instead and think it works more reliably.

- You should link to funcmap.go for all funcs available to templates. There are useful ones like has, etc too.

- Add some documentation on how data blocks are passed down (it seems this was not obvious given how HPDI was setup and the data blocks don't follow terraform style which forces you to repeat fields everywhere).

- terraform fmt should run by default through engine, do you mean don't disable it?

- One tip I have is sometimes a config is invalid and terraform fmt will fail so the output won't get copied over. So pass in --format=false and then see the broken file, fix it and then re-run engine with --format=true.

- one gotcha is if you generated a file and then updated your engine config to remove the file, it won't remove in the output. So you should delete the generated output and then re-generate. I was working on a feature to detect extra files but didn't get a chance to finish it, maybe one of you can take it on later.

**Comment by xingao267** [comment]
Updated the example to fix the pubsub topic dependency and added several docs in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/tree/master/docs/tfengine. PTAL.
