### ISSUE TITLE
Not able to generate any terraform file

### ISSUE THREAD

**Issue by gbohra** [GoogleCloudPlatform/healthcare-data-protection-suite#827]
I am running this application using command

> tfengine --config_path=devops.hcl --output_path=/Users/source/gcr/config/

There is no error and no file generated. How to debug this?

**Comment by MartinPetkov** [comment]
I think we need some more details to determine what's happening here:
1. What happens if you set `--outpu_path=.` flag? It should generate files in the current directory.
2. Does the target directory actually exist? Make sure there isn't a typo.
3. Which version are you using? Run `tfengine --version`.

It's unexpected for there to be no output and no generated files. You should see some kind of an error if it failed.

**Comment by gbohra** [comment]
Thanks Martin. Got the issue. Closing this.

**Comment by MartinPetkov** [comment]
For our interest, what was the problem?

**Comment by gbohra** [comment]
Getting this error
![image](https://user-images.githubusercontent.com/1699371/110148738-338fdd00-7e03-11eb-8735-d3a0567ffa49.png)

**Comment by gbohra** [comment]
this is still open issue. not able to identify the exact reason. new to the language and code. although, I am following proper document.

**Comment by MartinPetkov** [comment]
Could you give the full path of where you are? I see you're using the file `org_policies.hcl` but I'm not sure if that's `examples/tfengine/org_policies.hcl` or `templates/tfengine/recipes/org_policies.hcl`.

I can't reproduce this right now - at the latest master branch, the following works for me:
```
$ mktemp -d
/tmp/tmp.8O3yFghmjf

# Run from repo root
$ go run ./cmd/tfengine/ --config_path=./examples/tfengine/org_policies.hcl --output_path=/tmp/tmp.8O3yFghmjf
$  # No errors
```

Try running the command from the repo root and use the relative path to the `.hcl` file.
