### ISSUE TITLE
Managing cross project service account permissions (IAM)

### ISSUE THREAD

**Issue by jordan83** [GoogleCloudPlatform/healthcare-data-protection-suite#828]
In a complex system, there will be several separate deployments that are managed by CICD. Each deployment is typically centered around a single project. This makes it a bit awkward to manage service account IAM bindings that cross the project boundary.

We have typically solved this by using raw terraform which doesn't allow us to take advantage of some of the conveniences (and best practices) baked into the data protection suite. 

There should be a way to manage these cross project IAM bindings that is fully supported by the data protection suite. Ideally, this template would be centered around a group of members (SA, user) and would allow adding and removing roles from that group of members. That said, a better approach may exist.

**Comment by xingao267** [comment]
Since IAM permission is sometimes a special case and cross project boundaries, we can support another top level `iam` recipe in https://github.com/GoogleCloudPlatform/healthcare-data-protection-suite/tree/master/templates/tfengine/recipes, which centers around a IAM identity (sa, user or group) to apply any IAM bindings to it. We can also make the it a list to apply the same IAM bindings to all list members. The end user config can look like the following:

```
template "dataflow_iam" {
  recipe_path = "{{$recipes}}/iam.hcl"
  output_path = "./dataflow_iam"
  data = {
    members = [
      serviceAccount: xxx
      user: foo@example.com
    ]
    bindings = [
      {
        parent_type = "bucket" # "project", "bucket", "billing_accounts", etc
        parent_id = "<bucket_name>"
        roles = [
          "roles/storage.admin",
        ]
      },
      {
        parent_type = "project"
        parent_id = "<project_id>"
        roles = [
          "roles/compute.networkAdmin",
          "roles/dataflow.admin"
        ]
      },
    ]
  }
}
```
